[book]
authors = ["Pete Stenger"]
language = "en"
multilingual = false
src = "src"
title = "Fall CTF 2023 Guide"

[output.html]
mathjax-support = true
default-theme = "navy"
site-url = "/guide-2023/"
preferred-dark-theme = "navy"
git-repository-url  = "https://github.com/sigpwny/guides"
edit-url-template = "https://github.com/sigpwny/guides/edit/main/fallctf-2023/{path}"
additional-css = ["theme/css/custom.css"]
[output.html.code.hidelines]
python = "~"